services:

  mongo-db:
    container_name: funkos-db_mongo
    image: mongo:5.0
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./database/funkos.js:/docker-entrypoint-initdb.d/funkos.js:ro
    networks:
      - funkos-network

  funkos-api-rest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: funkos-api-rest
    restart: always
    env_file: .env
    ports:
      - ${API_PORT}:3000
    volumes:
      - storage-dir:/storage-dir
    networks:
      - funkos-network
    depends_on:
      - h2-db
      - mongo-db

networks:
  funkos-network:
    driver: bridge