services:

  # PostgresSQL
  postgres-db:
    container_name: funkos-db_postgres
    image: postgres:12-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - funkos-network

  # MongoDB
  mongo-db:
    container_name: funkos-db_mongo
    image: mongo:5.0
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./database/funkos.js:/docker-entrypoint-initdb.d/funkos.js:ro
    networks:
      - funkos-network

  # Servicio de la API REST
  funkos-tienda-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: funkos-tienda-api
    restart: always
    env_file: .env
    ports:
      - ${API_PORT}:3000
    volumes:
      - storage-dir:/app/storage-dir
    networks:
      - funkos-network
    depends_on:
      - postgres-db
      - mongo-db

volumes:
  storage-dir:

networks:
  funkos-network:
    driver: bridge