services:

  funkos-tienda-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: funkos-tienda-api
    restart: always
    env_file: .env
    ports:
      - ${API_PORT}:3000
    volumes:
      - storage-dir:/app/storage-dir
    networks:
      - funkos-network

volumes:
  storage-dir:

networks:
  funkos-network:
    driver: bridge